os: linux

language: cpp

script: ./travis/run-build.sh

compiler: gcc

branches:
  only: master

addons:
  apt:
    # For gcc-4.7
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - flex
    - bison
    - libtool
    - autoconf
    - libncurses5-dev
    - libprotobuf-dev
    - protobuf-compiler
    - gcc-4.7
    - g++-4.7

sudo: false
